<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>

<?php

    $id = $_POST["id"];


    $tareas = new TareasModel();
    $borrado = $tareas->eliminar($id);


?>

<p class="ml-10 text-2xl">
    <?php     if ($borrado ==false) {
        echo "Este id no existe, no se ha podido borrar.";
    } else {
        echo "Tarea eliminada !";
    }
    ?> </p>

</body>
</html>


