<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>


<a href=<?php echo WEB_ROOT . "/" ?>>
    <button class="ml-10 my-5 bg-blue-50 border-separate border-spacing-1 border border-slate-500 hover:bg-blue-700 text-blue-900 font-bold py-2 px-4 rounded-full">Home</button>
</a>
<br>

<?php echo $this->content(); ?>

    
</body>
</html>